project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  title: "Shaonlee Patranabis"
  sidebar:
    style: "docked"
    title: false
    search: false
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV

  page-footer:
    left: "Shaonlee Patranabis"
    center:
      - text: "Email"
        href: mailto:S.Patranabis@liverpool.ac.uk
      - text: "CV"
        href: cv.html
      - text: "GitHub"
        href: https://github.com/itsshaonlee
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?user=pqWmC4gAAAAJ&hl=en
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/shaonlee-patranabis-2541b649/
    right: "© 2025"

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 2
    highlight-style: github