project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Shaonlee Patranabis"
  navbar:
    pinned: true
    left:
      - text: "Research"
        href: "#research"
      - text: "About"
        href: "#about"
      - text: "CV"
        href: "#cv"
      - text: "Contact"
        href: "#contact"

  page-footer:
    left: "Shaonlee Patranabis"
    center:
      - text: "Email"
        href: mailto:S.Patranabis@liverpool.ac.uk
      - text: "CV"
        href: cv.html
      - text: "GitHub"
        href: https://github.com/itsshaonlee
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?user=pqWmC4gAAAAJ&hl=en
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/shaonlee-patranabis-2541b649/
    right: "© 2026"

format:
  html:
    theme: lux
    css: styles.css
    toc: false
    smooth-scroll: true
    highlight-style: github
